### ISSUE TITLE
[Feature] NEO Node selection instead of 'MainNet'

### ISSUE THREAD

**Issue by stickx** [CityOfZion/neon-js#428]
Pretty sure there isn't a way to do this, but if there is, please let me know :)

`Neon.api.default.sendAsset({
    net: 'MainNet',  // Would be nice to set this or similar to a node URL
    account: account,
    intents: Neon.api.makeIntent(intent, toAddress)
})`

**Comment by snowypowers** [comment]
We use `MainNet` here because underneath the hood, it is a 2 step process that requires a 3rd party data provider like neoscan to provide the details necessary to craft the transaction. 

If you don't care about the 3rd party part and just wishes to point it directly to your private neo node for stability, use `url` field to override. This will cause the program to request the data as usual from neoscan but use the `url` provided when actually sending the transaction to the network.
