### ISSUE TITLE
Add neoscan as fallback for API

### ISSUE THREAD

**Issue by canesin** [CityOfZion/neon-js#47]
There will always be moments where the neon-db has connectivity issues. Adding neoscan as a fallback will increase the reliability of the service, we are in desperate need for that. Every time there is a down period, no matter how small people go crazy and council loses 5 days of life.

neoscan API is supposed to offer all the needed info to neon-js, if it is not there - it is a issue. https://neoscan.io/doc/Neoscan.Api.html

**Comment by snowypowers** [comment]
Looked through the neoscan API. I do not see a endpoint which provides me the info:

1. Unclaimed transaction ids. This is needed to form the claimTransaction. I supposed i can calculate that from taking all txs - claimed txs but I will also need to know the amt of GAS claimable for each tx. This can be calculated by taking the difference between the blocks that generate and spent the coin. However, this means 2 API hits per transaction to hit.

2. Spendable coins. The current `get_balance` API only returns the balance but not the actual coins. In order to spend, I will require the individual transaction ids for each coin and their corresponding value. Currently I can infer them from the txids but I will need to hit the RPC/API to get the transaction in question to check for the coin value. This is not desirable.

**Comment by canesin** [comment]
Please create issues for (1) there, there is already a issue for (2).

**Comment by snowypowers** [comment]
This issue will depend on [#58](https://github.com/CityOfZion/neo-scan/issues/58) and [#59](https://github.com/CityOfZion/neo-scan/issues/59)

**Comment by saltyskip** [comment]
Why not have balance rely directly on RPC to full nodes? getAccountState is an RPC method that can be used, and should have hire availability. Balance Data (which is what most people worry about) would be more reliable in case of coz API downtime.

**Comment by canesin** [comment]
@saltyskip we need to do a NEP for RCP standard, the getbalance should contain the same required data to avoid many calls to the node.

**Comment by Ejhfast** [comment]
@snowypowers neoscan now supports the necessary API methods, maybe worth taking a look again

**Comment by snowypowers** [comment]
I will write up the support for Neoscan.

However I don't see the infrastructure up for test net? Wont be able to test fully if that is not available.

**Comment by Satoshinaire** [comment]
`https://neoscan-testnet.io/api/test_net/v1`

**Comment by Satoshinaire** [comment]
@snowypowers Is this what you need?
`https://neoscan-testnet.io/api/test_net/v1`

**Comment by snowypowers** [comment]
yeah but it looks like its not updated to the latest API version yet. Weird that you gotta change the url to TestNet in two places but whatever. I will encode this url as the testnet url for now.

**Comment by snowypowers** [comment]
#79 introduces neoscan support onto `dev`
