### ISSUE TITLE
[bug] using neon-js in a react-native project and running in Release mode fails

### ISSUE THREAD

**Issue by jankjr** [CityOfZion/neon-js#474]
Hi, we seem to have discovered an issue with a dependency in neon-js.

I am not exactly sure what causes it, but the issue seems to stem from depending on `loglevel`.  Many of `loglevel`s functions require that there is a correctly bound `this` context when calling the functions.

My theory is that somewhere after the bundling and rebundling the javascript, the module gets an incorrectly bound context attached, and fails to initialise.  I have tried including and initialising `loglevel` in a similar fashion to `neonjs`, but I can't seem to get the same unbound context. It only happens when including the neonjs distribution, and running the react-native app in a release configuration.

Running the app results in the following error 
```
2019-10-01 08:37:07.592 [error][tid:com.facebook.react.JavaScript] TypeError: this.methodFactory is not a function. (In 'this.methodFactory(a,t,n)', 'this.methodFactory' is undefined)
2019-10-01 08:37:07.597 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: this.methodFactory is not a function. (In 'this.methodFactory(a,t,n)', 'this.methodFactory' is undefined)
2019-10-01 08:37:07.597 [error][tid:com.facebook.react.JavaScript] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
2019-10-01 08:37:07.608510+0100 NeonJSRN[49146:24822405] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: this.methodFactory is not a function. (In 'this.methodFactory(a,t,n)', 'this.methodFactory' is undefined)', reason: 'Unhandled JS Exception: TypeError: this.methodFactory is not a function. (In 'this.methodFactory(a,t,n)', 'this.methodFactory' is undefined), stack:
n@544:208005
<unknown>@544:208910
[...about 20 lines more of a native stack trace that does not add anything]
```

I have create a minimal repo that displays the issue: https://github.com/jankjr/neon-js-rn-issue

It just imports the neonjs module, running the project in release mode `yarn run-release` causes the javascript error above.

I know this is probably an issue with the metro bundler that is used in react-native. But I am not exactly sure where and why this fails. We have solved it internally by building a forked version of neonjs without loglevel.

**Comment by snowypowers** [comment]
This sounds more like a bug with the bundler than the dependency itself since it was working in debug. You could try to run some javascript after loading the module in debug to ensure it works (call some neon-js methods that involves logging and also activate logging).

Some searching on the net turns up another similar issue that has to do with the bundler too. An alternative mentioned was https://github.com/callstack/haul. Maybe you can try and see if that works.

Good to hear that you have a workaround.

**Comment by metachris** [comment]
Just to note - this issue is affecting everyone who wants to use neon-js in react native with the default setup. I think it would be great if neon-js would just support that use-case as well, I'm sure other people would be happy about this too.

The way the loglevel dependency is coded is very browser specific. Not sure it adds that much value, and just removing it might be a really simple solution. Please consider it.

**Comment by comountainclimber** [comment]
Not sure when this changed but I was able to create a production expo build that does not crash using neon-js today. Demo project here => https://github.com/comountainclimber/expo-neon-js/tree/master

The only real gotcha was that `window.crypto` needed to be polyfilled. I did not encounter the error mentioned above

**Comment by comountainclimber** [comment]
This no longer seems to be an issue as of 8/6/2020... I was able to create a react-native iOS production binary using neon-js without any issues... 

The only gotcha was that `window.crypto` needed to be polyfilled. If anyone is looking for an example of how I got this working it can be found here => https://github.com/comountainclimber/expo-neon-js
