### ISSUE TITLE
Does this SDK support getting OPTCODE from BYTECODE of the transaction?

### ISSUE THREAD

**Issue by Shirley-Ji** [CityOfZion/neon-js#487]
Hi guys,

there is a script param in transaction, like verificationscript, invocationscript, script etc. Is there any method supporting transferring between OPTCODE from BYTECODE  of these scripts?

Thanks,
Shirley

**Comment by hal0x2328** [comment]
It's possible to use neon-js to convert a single byte to its opcode since you have access to the `OpCode` enum exported by the `sc` module but there's no disassembler module to disassemble all the instructions taking into account their operand lengths and values.

I wrote a disassembler module for the Neo3 preview explorer, you could always try backporting it to the Neo2 opcode/syscall instruction set:

https://github.com/CityOfZion/neo-3-preview/blob/master/src/utils/disassemble.js

(One "gotcha" here that makes it not quite as simple as swapping out the lists of opcodes/method names: in Neo2 you can specify a syscall either by method name or its 4-byte hash, and in Neo3 the use of method names has been discarded - so you'd need to modify the code to support both types of operands.)

**Comment by Shirley-Ji** [comment]
@hal0x2328 Thx, that's cool! I also found a js from https://neocompiler.io/#!/ecolab/conversor, sharing with you.
