### ISSUE TITLE
Compute expected txid from transaction object

### ISSUE THREAD

**Issue by Ejhfast** [CityOfZion/neon-js#50]
This will make some interactions with wallet cleaner, especially two-step things like claim

**Comment by snowypowers** [comment]
Currently, you can get the txid by passing in the complete transaction through `getTransactionHash`.  Since this is an important part of the query, what I suggest happen is that the API will attach the txid with the response if `true` is returned.

Current response from `doSendAsset`:

```js
{
'jsonrpc': '2.0',
'id': '1',
'result': true
}
```

Intended response from `doSendAsset`:

```js
{
'jsonrpc': '2.0',
'id': '1',
'result': true,
'txid': 'exampleTxIdToPasteIntoBlockExplorer'
}

```
