### ISSUE TITLE
Multisig Helper Functions

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#591]
This feature incorporates helper functions for multisig addresses.  While not heavily used in typical applications, this functionality is critical for initial node deployment and access to tokens.

**Comment by snowypowers** [comment]
Current multisig support:

- All methods within neon-core/src/wallet/multisig.ts
	- constructMultiSigVerificationScript
	- getPublicKeysFromVerificationScript
	- getSigningThresholdFromVerificationScript
	- getSignaturesFromInvocationScript
- Account.createMultiSig(signingThreshold: number, publicKeys:string[]) => Account
	Static method for creation of an Account object by assembling the verification script.
- Witness.buildMultiSig(tx:string, sigs: (string|Witness)[], acctOrVerificationScript: Account|string) => Witness
	Static method for combining the many signatures into a single Witness object.

As of now, multisig is working with a integration test in neon-core/__integration__/wallet/multisig.ts.

**Comment by ixje** [comment]
I somehow think the intention here was to add [this helper function](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/SmartContract/Helper.cs#L48]). Because that is required for solving a part of https://github.com/CityOfZion/neon-js/issues/581

**Comment by ixje** [comment]
@kjlevitz I just realized we have to update the `function is_multisig_contract(signature_script)` signature to return the public key and signature counts if end result would be `true`. I need that information for being able to calculate the network fee ([ref](https://github.com/neo-project/neo/blob/9a160c4d249efb7364c9dbbed847fa1ded72604b/src/neo/Wallets/Wallet.cs#L417-L425))

My idea is to optionally pass an object that can be updated. So something like this
```typescript
interface SignParamsLike {
   public_key_count: number;
   signature_count: number;
}

function is_multisig_contract(signature_script: string, state?: SignParamsLike) {
    // do multisig checks
    if (state) {
        state.public_key_count = public_key_count;
        state.signature_count = signature_count;
    }
    return true;
}
```

**Comment by kjlevitz** [comment]
https://github.com/kjlevitz/neon-js/blob/next/helpers/signatureVerification.ts

Current verification helper that I have been working on. If this looks good for single and multi-sig I can create a PR to next branch.

**Comment by snowypowers** [comment]
How about using `getPublicKeysFromVerificationScript` or `getSigningThresholdFromVerificationScript` which are already implemented? Account has a `isMultiSig` method but it does not verify that the verification script is well-formed.

**Comment by ixje** [comment]
Ugh..unfortunate to learn now there was already some support. Yes those 2 functions could extract the public key and required signature counts from a verification script. 

Current state
* no `isSingleSignature()` helper
* the `isMultiSig()` has limited format checking and is coupled to an `Account`. However, it is likely enough from a transaction building perspective (assuming the user doesn't try to manually build a verification script).

I tend to lean towards saying strict checking is better, especially because the network fee is calculated based on the instructions/data present in the script.

How about the following?
* We include the 2 helper functions somewhere, perhaps without the `SignParamsLike` argument for the `is_multisig_contract()` function because there are existing methods for that. I'm hoping to get a recommendation for a location from you @snowypowers 
* We point https://github.com/CityOfZion/neon-js/blob/1dd34bdec3a166f2687faa333d2312f331ab66b9/packages/neon-core/src/wallet/Account.ts#L160 to use the new multisig helper function
 
The net result is we have stricter checking and we decouple verification script checking capabilities from the `Account`, making it re-usable. It would then for example allow somebody to import a raw transaction and easily check all witnesses for its type of verification script. That would currently require a temporary `Account` object where one replaces the `contract.script` with the verification script of the witness such that `isMultiSig()` can be called.

**Comment by snowypowers** [comment]
Im good with stricter checking. `isMultiSig` has a clear use case here. Not sure `isSingleSignature`'s use case. This issue is specifically for Multisig anyway. Lets move forward with the multisig focus here and open another issue for single signatures.

My view is that we can have the following functions:

1. `isMultiSig` which verifies the correctness of the verification script.
2. `getPublicKeysfromVerificationScript` which extracts the public keys *without verification*
3. `getSigningThresholdFromVerificationScript` which extracts the threshold *without verification*.

I would expect the proper use case to be:

```
if (isMultiSig(script)) {
const publicKeys = getPublicKeysfromVerificationScript(script);
const threshold = getSigningThresholdFromVerificationScript(script);
}
```

So we can reduce the amount of checking code in the two getter functions. All of them can sit in the `multisig` file that the getters are currently and yes we point the Account class to use the new `isMultiSig`.

**Comment by ixje** [comment]
The `isSingleSig()` is again needed for #581, specifically for https://github.com/neo-project/neo/blob/9a160c4d249efb7364c9dbbed847fa1ded72604b/src/neo/Wallets/Wallet.cs#L410-L414

Arguably it can be hardcoded in the fee calculation function, but it could also work in the decoupling example given before. A witness verification script basically be anything the user wants and this would give the user a way of checking if a witness is standard or not.

**Comment by lllwvlvwlll** [comment]
resolved
