### ISSUE TITLE
Sunsetting notifications server

### ISSUE THREAD

**Issue by corollari** [CityOfZion/neon-js#624]
I've been running the servers that serve notifications for [neo-PubSub](https://github.com/corollari/neo-PubSub) for over half a year now, but as a college student with no income I don't have the funds available to continue running them (most of the cost comes from having to maintain neo nodes for both mainnet and testnet). Due to this I'll have to sunset the service, but given that it's integrated into neon-js (the neo2 version) I think it's best to coordinate with you in order to ensure the best transition.

How do you believe it's best to proceed?

**Comment by snowypowers** [comment]
We can turn it down and remove the code or potentially ask if there is any org that wishes to take over. Do you have some rough numbers?

- Amount of activity on the endpoints (eg. Amount of usage on mainnet/testnet per day or per month)
- Cost of maintaining the full stack per month.

If we can do a simple cost benefit analysis, the decision might be clearer.

**Comment by corollari** [comment]
I don't run any analytics on it but I'll add some and report after some data has been collected

**Comment by corollari** [comment]
Actually it turns out that the logs hold the number of subscribed clients, so I looked into it and right now that number is 8. So, overall:
- At the moment, there's 8 clients subscribed to events
- The cost of maintaining the whole thing is ~200€/mo
  - Websockets: 14$/mo. These are two heroku "hobby" dynos ($7/mo each) that distribute the events on mainnet and testnet
  - NEO nodes: ~200$/mo. These are two instances (mainnet & testnet) of the neo client running on AWS EC2 containers.

Do you have any numbers that this could be compared against?

> We can turn it down and remove the code

I see, so just remove that part of the code and release a new version on npm? Could projects that are stuck with an old version of neon-js run into problems?

**Comment by snowypowers** [comment]
Paying 200 for 8 clients seems a bit too much hahaha.

Yes projects utilizing it will run into issues but the code is still there so they can host it themselves. I doubt there will be since your initial data seems to indicate little usage.

Yea we just have to remove the code. However, since the source code is available, we can leave it there and people can just host it themselves. I dont think its a big issue.

**Comment by corollari** [comment]
What are your thoughts on replacing the current notification code with one compatible with neo-go's notifications? This would be a breaking change since the same information is not provided by their API. Furthermore, you mentioned earlier this year that you don't expect to release any new major versions of neon-js for neo2, so I was wondering if you believe this is a change that is worth working on and releasing or if it's better to just wait for neo3.

**Comment by snowypowers** [comment]
I think it would be great if the community converges on a single spec across all languages. However, I wouldn't be rushing to implement it if there is no demand for it. I would prefer not to implement it for now unless we get sufficient asks for it.

On a side note, neo2 will not release any new major versions since neo3 will take over in terms of major versions. For neo2, we will simply abandon semantic versioning but version in a reasonable manner.

**Comment by corollari** [comment]
Got it :+1:, I will then close this since #634 has already been merged.
