### ISSUE TITLE
invokeFunction returns  Error with params

### ISSUE THREAD

**Issue by ediopia** [CityOfZion/neon-js#706]
Operations without params work okay such as symbol or decimals however with any params it returns [Object reference not set to an instance of an object]

My code was 
const result = await rpcClient.invokeFunction(
  CONST.NATIVE_CONTRACT_HASH.GasToken,
  "balanceOf",
  [input.fromAccount.scriptHash]
);

**Comment by snowypowers** [comment]
What is happening is that is an error thrown by the NEO RPC endpoint. You can try by doing a curl with the following payload (which is very similar to what your code will produce) :

```
{
    "jsonrpc": "2.0",
    "method": "invokefunction",
    "params": [
        "d2a4cff31913016155e38e474a2c06d08be276cf",
        "balanceOf",
        [
            "b611bfa60886125e0071b56deeaf6efb40bd2336"
        ]
    ],
    "id": 3
}
```

You will get:

```
{
    "jsonrpc": "2.0",
    "id": 3,
    "error": {
        "code": -2147467261,
        "message": "Object reference not set to an instance of an object.",
        "data": "   at Neo.SmartContract.ContractParameter.FromJson(JObject json)\n   at Neo.Plugins.RpcServer.<>c.<InvokeFunction>b__39_0(JObject p)\n   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()\n   at Neo.Plugins.RpcServer.InvokeFunction(JArray _params)\n   at Neo.Plugins.RpcServer.ProcessRequest(HttpContext context, JObject request)"
    }
}
```

The root cause is that the RPC endpoint is now stricter in terms of arguments and is taking only ContractParam objects. I will work to restrict the inputs of the invoke methods. For your case to work, please rely on the ContractParam helpers to craft your arguments:

```diff
const result = await rpcClient.invokeFunction(
CONST.NATIVE_CONTRACT_HASH.GasToken,
"balanceOf",
- [input.fromAccount.scriptHash]
+ [ContractParam.hash160(input.fromAccount.address)]
);

```

This assumes that your `input.fromAccount` is a `Neon.wallet.Account` class.

You might also find [this test](https://github.com/CityOfZion/neon-js/blob/f63521e413740c62865551fc6c1398b5dbb74950/packages/neon-core/__integration__/rpc/RPCClient.ts#L268) useful as a reference.

**Comment by ediopia** [comment]
Solved. Thanks for your help!
