### ISSUE TITLE
invokeScript doesn't work properly

### ISSUE THREAD

**Issue by ediopia** [CityOfZion/neon-js#707]
const sb = new sc.ScriptBuilder();
  sb.emitAppCall(CONST.NATIVE_CONTRACT_HASH.GasToken, "decimals");
  try {
    const rpcClient = new rpc.RPCClient(inputs.nodeUrl);
    const result = await rpcClient.invokeScript(sb.build());
    console.log(result);
  } catch (e) {
    console.log(e);
  }

It returns [Invalid params].

**Comment by snowypowers** [comment]
In N3, the rpc `invokescript` requires a base64 encoded string. Without a strict typing, the code is unable to tell if your input is base64 or hex, thus it will leave it alone. You will have to manually encode it yourself or use the `u.HexString` class to wrap your input so that the typing is explicit and the code can help you with the encoding. 

Please refer to this [test](https://github.com/CityOfZion/neon-js/blob/f63521e413740c62865551fc6c1398b5dbb74950/packages/neon-core/__integration__/rpc/RPCClient.ts#L300) for a working example.

**Comment by ediopia** [comment]
Solved. Thanks for your help!
