### ISSUE TITLE
Completing information that comes from APIs

### ISSUE THREAD

**Issue by endkeyCoder** [CityOfZion/neon-js#742]
The properties "sysFee" and "generated" were added to "ClaimItem" class and "ClaimItemLike" Interface. The "assetHashes" property was also added to the result of the function "getBalance", for it to be possible, the property "assetHashes" was added to the "Balance" class and the property "asset_hash" to the "NeoscanBalance" interface.

motivation: Currently, the Neon Wallet app uses the Neoscan API directly to have access to the blockchain data. It was  verified that neon-js uses the same APIs to obtain the data. Knowing this, the app will no longer use the APIs (like it currently does) and instead will use neon-js functions. But some data that is returned by the API is not returned by these functions, therefore it is necessary to include that information

**Comment by snowypowers** [comment]
It does seem like the implementation is converging towards the neo-cli implementation so it should be no problem supporting both new features. 

Within `neon-js`, the distinction between a token and an asset is made quite clear. I would rather keep this intact rather than go with the conflation of meaning that the official implementation went with. For this case, I prefer that the `hash` property is added to the `AssetBalance` class and then we introduce a `tokenHashes` property on the `Balance` class (which prevents modification of the old `tokens` field).
