### ISSUE TITLE
Support in Nep17Contract for the ability to send multiple assets in a single transaction

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-js#754]
Currently the experimental `Nep17Contract` class only supports a single "transfer" in a transaction however I think the class _should_ support the ability for multiple transfers in a single transaction. Not sure what the best path forward would be to add this support but wanted to create the issue to get the discussion started

**Comment by snowypowers** [comment]
Can you clarify what kind of `multiple transfers in a single transaction` mean? I will focus on the 2 likely scenarios happening in NeonWallet:

1. Account A sending Token T to Account B and Account C
2. Account A sending Token T and Token U to Account B (and more recipients)

The issue here with the experimental class is that:

1. `Nep17Contract` is a single contract view. This means that scenario 2 cannot be fulfiled correctly from this single class as it does not make sense to trigger multiple contracts from a class that is meant to represent a single contract.

2. The contract is constructed with a RPC client and the API does not expose a way to construct an intent. All the API directly calls the the RPC node. This is great for prototyping and simple flows but does limit the flexibility of the API.

All of the functionality offered in the nep17 contract code is actually provided in the NetworkFacade layer (albeit with more verbose syntax). If you are looking for complex flows, I would prefer a network view (I am interacting with the MainNet as opposed to I am interacting with a single specific contract).

Also importantly, what is great about the experimental classes that should be incorporated into the main API? What features do you like from it over the existing features available that are supported?

With this discussion, hopefully, we can extract the use cases and migrate them out of the experimental folder so that we do not have to maintain separate sets of code.

+ @ixje for notification as he is the one who designed the experimental code.

**Comment by comountainclimber** [comment]
Thanks for quickly responding to this issue/discussion point!

`Account A sending Token T and Token U to Account B (and more recipients)`

☝️ this is the specific scenario I had in mind when creating this issue...

After reading your comment here I do agree that it does not make sense to put this functionality into the "single contract abstraction" I will go ahead and take a closer look at the NetworkFacade layer.

The benefits I see of the experimental classes is that their API is substantially more simple than more complex flows and it keeps reading/maintaining wallet code much more simple. I do like the idea of creating a new module within neon-js to contain the experimental code  👀
