### ISSUE TITLE
Unable to transfer nep17 other then GAS or NEO using NetworkFacade class

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-js#760]
When attempting to perform a transfer using a nep17 other then GAS or NEO the following error occurs:

`Unable to validate transaction`

I was able to reproduce this by attempting to transfer the following token using the NetworkFacade `transferToken` method => https://dora.coz.io/contract/neo3/testnet/0x0a8b0c0b1981738f468dc630220df18fbb85ff87

**Comment by hal0x2328** [comment]
Because the facade does a validation check on the transaction but the `validateScript` function doesn't include a signer, the validation faults and the transaction fails to be sent. Not sure why it works for NEO/GAS but not non-native NEP17 tokens.

https://github.com/CityOfZion/neon-js/blob/3cc5330d0b4450bd5530cc748c11bc59a637316f/packages/neon-api/src/transaction/validator.ts#L97

https://github.com/CityOfZion/neon-js/pull/486 seems to be related, this may be an unintended side-effect of that?
