### ISSUE TITLE
RPCClient.getRawTransaction returns a base64 string but Transaction.deserialize expects a hex string

### ISSUE THREAD

**Issue by devhawk** [CityOfZion/neon-js#764]

**Comment by ixje** [comment]
Going to close as stale. 

Personally I would prefer the data to be decoded, but I do think this is by design. Other calls like `getBlock` and `getStorage` also do not decode the results. There are also quite a few RPC return types that hold base64 encoded values.

[Recently](https://github.com/CityOfZion/neon-js/issues/849#issuecomment-1144486993) Snowy said the following
> Traditionally, I would expect an RPC client to merely return the data or slightly decorate the data for readability.
which to me strengthens the assumption that it is by design. Of course we could argue if base64 decoding is decorating or not.
